spring:
  ai:
    openai:
      base-url: ${AI_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode}
      # 参考官方文档获取 API Key
      # https://help.aliyun.com/zh/model-studio/first-api-call-to-qwen?spm=a2c4g.11186623.help-menu-2400256.d_0_0_1.30237dc5FLsnId
      api-key: ${AI_API_KEY}
      chat:
        options:
          model: ${AI_CHAT_MODEL:qwen3-max}
  config:
    name: win-diag-doctor

  security:
    user:
      # 默认管理员账号密码，可通过环境变量覆盖
      name: ${WDD_USER_NAME:admin}
      password: ${WDD_USER_PASSWORD:admin}
      roles: ADMIN

  autoconfigure:
    exclude:
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeChatAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration

wdd:
  probe:
    template-path: data/probe-templates
    # 默认连接密钥，用作哈希盐值，可通过环境变量覆盖
    connect-key: ${WDD_PROBE_CONNECT_KEY:default_connect_key}

  prompts:
    locale: zh # TODO: add more locales

  agent:
    think-model: ${WDD_AGENT_THINKING_MODEL:${AI_CHAT_MODEL}}
    flash-model: ${WDD_AGENT_FLASH_MODEL:${AI_CHAT_MODEL}}


server:
  port: 8093
  forward-headers-strategy: native