spring:
  application:
    name: win-diag-doctor-app

  security:
    user:
      # 默认管理员账号密码，可通过环境变量覆盖
      name: ${WDD_USER_NAME:admin}
      password: ${WDD_USER_PASSWORD:admin}
      roles: ADMIN
wdd:
  ai:
    base-url: ${AI_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode}
    api-key: ${AI_API_KEY} # 必填，不设默认值以 Fail Fast
    default-model: ${AI_CHAT_MODEL:qwen-max} # 全局默认模型

    think-model: ${WDD_AGENT_THINK_MODEL:${wdd.ai.default-model}}
    flash-model: ${WDD_AGENT_FLASH_MODEL:${wdd.ai.default-model}}

    timeout: 60s

  probe:
    template-path: data/probe-templates
    # 默认连接密钥，用作哈希盐值，可通过环境变量覆盖
    connect-key: ${WDD_PROBE_CONNECT_KEY:default_connect_key}

  prompts:
    locale: zh # TODO: add more locales

server:
  port: ${SERVER_PORT:8093}
  forward-headers-strategy: native
