name: Build Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/src/**'
      - '**/pom.xml'
      - 'pom.xml'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/docker-build.yml'

  workflow_dispatch:

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # caching for docker layers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: win-diag-doctor:latest
          outputs: type=docker,dest=/tmp/win-diag-doctor-image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-diag-doctor-docker-image
          path: /tmp/win-diag-doctor-image.tar
          retention-days: 90
